### PR TITLE
Rewrite dynamic programming section

### PR DESCRIPTION
**Pull request by ozan**
@elenasharma do you mind reviewing?

I have replaced the somewhat confusing change making example with fibonacci and lattice traversal. Hopefully this gets the idea across more clearly.

I've also moved the diagrams over to svg to make future edits easier (FYI @aleksharma12 ). The trees are drawn with d3 but the lattices are just handwritten svg :smile: 

You should be able to run this locally by running `npm install` and then `./run dev`.

### CODE REVIEW

**Comment by elenasharma** [comment]
@ozan I really like the new examples - they are much clearer!

Something that I might change throughout this section is the use of the words "straightforward" or "obvious" to describe the solutions that are implemented for the example problems. Reading along, I found that the implementations were not always immediately obvious or straightforward and sometimes required a few reads.

Another thing that could be even clearer is the jump in logic for the lattice traversal to the idea that each cell can store the current number of paths to that point. I felt that the explanation was strongest in the second and third sentences of the paragraph beginning "In this case, we can use a list of lists to store...". It might be nice to further explore how the decision was made to approach the problem in this way, rather than beginning this section with implementation details.

**Comment by ozan** [comment]
@elenasharma thanks for the edits! I'm going to go through and make the "obvious" stuff a little more obvious :smile: . I'll also better explain the dynamic programming strategy for the lattice traversal problem.

**Comment by ozan** [comment]
@elenasharma care to take another look?

**Comment by ozan** [comment]
@elenasharma FYI I'm going to merge this so that it's available for other readers, but feel free to review 6341868 retrospectively and make a PR for any suggested changes.

**Comment by elenasharma** [comment]
@ozan Sorry for the late reply on this, didn't see your comment earlier! I will make sure to review your updates :)

**Pull request merged**
